// <auto-generated />
using CommandLineApi.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CommandLineApi.Migrations
{
    [DbContext(typeof(CommandLineDbContext))]
    [Migration("20220522053552_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("CommandLineApi.Infrastructure.Models.Command", b =>
                {
                    b.Property<string>("CommandId")
                        .HasColumnType("text");

                    b.Property<string>("CommandName")
                        .HasColumnType("text");

                    b.Property<string>("CommandSnippet")
                        .HasColumnType("text");

                    b.Property<string>("OS")
                        .HasColumnType("text");

                    b.Property<string>("TargetEnvironment")
                        .HasColumnType("text");

                    b.HasKey("CommandId");

                    b.ToTable("Commands");
                });
#pragma warning restore 612, 618
        }
    }
}
